name: build
on:
  workflow_dispatch:
  pull_request:
    branches: ["*", "!latest"]
  push:
    branches: [latest, main]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Install deps
        run: yarn install

      - name: Fix sorting
        run: yarn sort

      - name: Fix formatting
        run: yarn format

      - name: Check lint
        run: yarn lint

      - name: Clean Project
        run: yarn clean

      - name: Build project
        run: yarn build

      - name: Test project
        run: yarn test

      - name: Run Project
        run: yarn google-rank --help

      - name: Check diff
        run: git diff --exit-code HEAD
