name: test
on:
  workflow_dispatch:
  pull_request:
    branches: ["*", "!latest"]
  push:
    branches: [latest, main]
jobs:
  package:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0

      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: latest

      - name: Enable Corepack
        run: corepack enable

      - name: Update Yarn
        run: yarn set version stable

      - name: Cache deps
        uses: actions/cache@v3.3.1
        with:
          path: .yarn
          key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install deps
        run: yarn install

      - name: Clean dist
        run: yarn clean

      - name: Build dist
        run: yarn nx build

      - name: Check diff
        run: git diff --exit-code HEAD

      - name: Test lib
        run: yarn test

      - name: Run bin
        run: yarn google-rank --help
