name: test
on:
  workflow_dispatch:
  pull_request:
    branches: ["*", "!latest"]
  push:
    branches: [latest, main]
jobs:
  package:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Install deps
        run: yarn install

      - name: Clean dist
        run: yarn clean

      - name: Build dist
        run: yarn build

      - name: Check diff
        run: git diff --exit-code HEAD

      - name: Test lib
        run: yarn test

      - name: Run bin
        run: yarn google-rank --help
